# Pre-commit settings / QA
# Angel Martinez-Tenor. 2022

# Instructions: https://pre-commit.com/
# Manual QA: 'pre-commit run --all-files'
# Update all versions: 'pre-commit autoupdate'
# Advanced QA (no pre-commit): pylint src --max-line-length 120
# Also: pylint $(git ls-files '*.py') --max-line-length 120

# Credits:
# Adapted from Angel Martinez-Tenor personal repo:
# https://github.com/angelmtenor/data-science-keras/blob/master/.pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first
    # - id: check-added-large-files
    #   args: ['--maxkb=2000']

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args: ['--line-length=120']

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py38-plus]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ['--line-length=120', '--profile', 'black']
    name: isort (python)
    # stages: [commit]
    # language: system
    # entry: isort
    # types: [python]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
# - repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    args: ['--max-line-length=120',
          '--per-file-ignores=__init__.py:F401']

# # - repo: https://github.com/pre-commit/mirrors-mypy
# #   rev: 'v0.991'
# - repo: local
#   hooks:
#   - id: mypy
#     name: mypy
#     entry: mypy
#     language: system
#     verbose: true
#     args: [--show-error-codes, --no-strict-optional, --ignore-missing-imports]
#     # additional_dependencies: [tokenize-rt==3.2.0, types-PyYAML]

# # - repo: https://github.com/pycqa/pylint
# #   rev: 'v2.15.8'
# -   repo: local
#     hooks:
#     -   id: pylint
#         name: pylint
#         entry: pylint $(git ls-files '*.py')
#         language: system
#         args:
#         - --max-line-length=120
#         # - --ignore-imports=yes
#         # - -d duplicate-code

-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=90]

# - repo: https://github.com/dosisod/refurb
#   rev: v1.3.0
#   hooks:
#     - id: refurb

# --- JUPYTER NOTEBOOKS ONLY ---

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:

    - id: nbqa-black
      args: ['--line-length=120']
    # - id: nbqa-isort
    #   args: ['--line-length=120']
    # - id: nbqa-flake8
    #   args: [--max-line-length=120]
    # args: [--nbqa-mutate]

- repo: local
  hooks:
  - id: jupyter-nb-clear-output # Note: jupyter_contrib_nbextensions needed
    name: jupyter-nb-clear-output
    files: \.ipynb$
    entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
    language: system
    exclude: ^notebooks/execution_caller.ipynb


# Check cyclical dependencies:
# - repo: https://github.com/tox-dev/pipdeptree
#   hooks:
#   - id: pipdeptree
#     args: ['--warn', 'fail']
